### ISSUE TITLE
HTTP 500 error at startup

### ISSUE THREAD

**Issue by dcoraboeuf** [structurizr/onpremises#11]
Hi,

We're using the version `2876`, deployed using Tomcat.

The application stops immediately after the startup with:

```
05-Dec-2022 16:09:55.928 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [6264] milliseconds
[ERROR] 2022-12-05 16:09:57.968 [http-nio-8080-exec-1] Http500Controller - null
```

It used to work very well a couple of days ago, until we had an out-of-disk-space issue. We restarted the app after the disk size was increased and this problem started to appear, making the app not available at all.

Is there a way to get more information in the logs about the root cause of this error?

Thanks,
Damien

**Comment by simonbrowndotje** [comment]
There's a `log4j2.properties` file inside the on-premises installation (`/WEB-INF/classes`) ... you can modify the `info` and `warn` values to `debug`, and restart to get more detailed logging.

**Comment by daniel-landowski** [comment]
Thanks @simonbrowndotje for the hint.

What we do is we run the structurizr war file in bitnami tomcat container. We correctly change the `/WEB-INF/classes/log4j2.properties` file in the war file, but upon deployment of the war the log4j2.properties appears in:

- `/var/lib/jetty/webapps/ROOT/log4j2.properties`

but we would expect this change to appear in:

- `/bitnami/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.properties`

Sadly, it is not visible there.

Would you recommend going the docker way instead of repackaging the war (like we do now).

**Comment by simonbrowndotje** [comment]
Can this issue be closed?

**Comment by daniel-landowski** [comment]
What do you think @dcoraboeuf ? (From my perspective we can close this issue.)

**Comment by dcoraboeuf** [comment]
That's OK for me too. Thanks.
