### ISSUE TITLE
Allow named versions

### ISSUE THREAD

**Issue by dimitrisfasoulas** [structurizr/onpremises#17]
It would be nice to have a way to assign labels to versions so we can reference the architecture of a specific system at a specific version

**Comment by simonbrowndotje** [comment]
1. My view of the on-premises installation is that it's a way to *publish* software architecture diagrams/documentation, rather than being a *repository* for them. My recommended usage pattern is to retain your workspace source (i.e. DSL, Markdown, etc) in something like git, and use the Structurizr CLI/Lite to push your workspace to the on-premises installation for viewing by a wider audience. With this usage pattern, since you have the workspace source in something like git already, I'd recommend using that mechanism for tagging workspace versions. If your workspace source resides next to the source code it's describing, then everything is tagged. It then becomes a simple task to checkout a particular version (tag), and push it to the on-premises installation, or use Lite, to view it.

2. "Structurizr versions" are deleted after a period of time (see `structurizr.maxWorkspaceVersions` in `structurizr.properties`).

For these reasons, adding support for named versions isn't something I plan to add. The codebase is now open source, so you're welcome to fork and add as needed.
