### ISSUE TITLE
API timeout when putting workspace

### ISSUE THREAD

**Issue by vedeja** [structurizr/onpremises#67]
### Description

When using the CLI to push a workspace to the structurizr/onpremises:3142 API, the request times out and the CLI logs ""java.net.SocketTimeoutException: Read timed out". Even though this error is logged, the UI is updated with the new workspace, and seems to be working fine from that perspective.

### Steps to reproduce

1. Run structurizr/onpremises:3142 exposed as https://myapp
2. docker run --rm -v myfolder:/usr/local/structurizr structurizr/cli push -url https://myapp/api -id 1 -key mykey -secret mysecret -workspace workspace.json -merge false -archive false

Expected result:
* The workspace is updated in the UI
* No error from CLI

Actual result:
* The workspace is updated in the UI
* Error from CLI: java.net.SocketTimeoutException: Read timed out

### Severity

Minor

### Priority

Low

### Resolution

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
I am unable to reproduce this, so it's likely related to something in your environment ... either the size of your workspace, or whatever tech you're using to route traffic to the app via `https://myapp`.

**Comment by danhan79** [comment]
I found that the default search setting, lucene, takes a long time to index and the structurizr cli times out.

**Comment by vedeja** [comment]
Setting `structurizr.search=none` appears to help. But of course leaves us with no search feature.

**Comment by vedeja** [comment]
I’m also curious about if pushing the workspace basically immediately after starting structurizr is part of the potential lucene overload.

**Comment by andrey-dubnik** [comment]
For me it was removing the write.lock from the index directory. Seem on some stage when JVM crashes leaving the lock file and the only way is to clean it manually as JVM won't know if this is safe to do so. 

Removing the lock on the app startup could fix the issue considering there is only one process.

**Comment by simonbrowndotje** [comment]
I suspect this is environment/configuration related, but you're welcome to reopen if with details on how to reproduce it.

**Comment by sts-rafalmazgaj** [comment]
Hey, I have the same problem right now. I wanted to set up CI/CD from GitLab to Structurizr, but after pushing, I get a 504 error (timeout). The error happens on the PUT operation. I'm sending a part of the logs. But in Structurizr, there are 3 saves.


> $ docker run --rm -v "$PWD:/workspace" structurizr/cli:latest push -id "${WORKSPACE_ID}" -key "${API_KEY}" -secret "${API_SECRET}" -workspace /workspace.dsl -url "${API_URL}" -debug
11:53:25.426 [main] INFO  com.structurizr.cli.PushCommand - Pushing workspace 2 to https://structurizr.foo/api
11:53:25.430 [main] INFO  com.structurizr.cli.PushCommand -  - creating new workspace
11:53:25.430 [main] INFO  com.structurizr.cli.PushCommand -  - parsing model and views from /workspace.dsl
11:53:25.563 [main] INFO  com.structurizr.cli.PushCommand -  - merge layout from remote: true
11:53:25.563 [main] INFO  com.structurizr.cli.PushCommand -  - pushing workspace
11:53:25.727 [main] INFO  com.structurizr.api.WorkspaceApiClient - Getting workspace with ID 2
11:53:25.737 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Request
11:53:25.737 [main] DEBUG com.structurizr.api.WorkspaceApiClient - HTTP method: GET
11:53:25.737 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Path: /api/workspace/2
11:53:25.738 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: User-Agent=structurizr-cli/
11:53:25.738 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: X-Authorization=[MASKED]:MQ==
11:53:25.738 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: Nonce=1752494005735
11:53:25.986 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Response
11:53:25.987 [main] DEBUG com.structurizr.api.WorkspaceApiClient - HTTP status code: 200
11:53:25.987 [main] DEBUG com.structurizr.api.WorkspaceApiClient - ---Start content---
11:53:25.987 [main] DEBUG com.structurizr.api.WorkspaceApiClient - { ... }
11:53:25.990 [main] DEBUG com.structurizr.api.WorkspaceApiClient - ---End content---
11:53:26.324 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Request
11:53:26.324 [main] DEBUG com.structurizr.api.WorkspaceApiClient - HTTP method: PUT
11:53:26.324 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Path: /api/workspace/2
11:53:26.324 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: User-Agent=structurizr-cli/
11:53:26.325 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: X-Authorization=[MASKED]:ZQ==
11:53:26.325 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: Nonce=1752494006323
11:53:26.325 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: Content-MD5=XXXXXXXXXXX
11:53:26.325 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Header: Content-Type=application/json; charset=UTF-8
11:53:26.325 [main] DEBUG com.structurizr.api.WorkspaceApiClient - ---Start content---
11:53:26.325 [main] DEBUG com.structurizr.api.WorkspaceApiClient - { ... }
11:53:26.326 [main] DEBUG com.structurizr.api.WorkspaceApiClient - ---End content---
11:53:26.327 [main] INFO  com.structurizr.api.WorkspaceApiClient - Putting workspace with ID 2
11:56:26.358 [main] DEBUG com.structurizr.api.WorkspaceApiClient - Response
11:56:26.358 [main] DEBUG com.structurizr.api.WorkspaceApiClient - HTTP status code: 504
11:56:26.358 [main] DEBUG com.structurizr.api.WorkspaceApiClient - ---Start content---
11:56:26.358 [main] DEBUG com.structurizr.api.WorkspaceApiClient - html>
head><title>504 Gateway Time-out</title></head>
body>
center><h1>504 Gateway Time-out</h1></center>
hr><center>nginx</center>
/body>
/html>
11:56:26.358 [main] DEBUG com.structurizr.api.WorkspaceApiClient - ---End content---
11:56:26.360 [main] ERROR com.structurizr.api.WorkspaceApiClient - com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
com.structurizr.api.StructurizrClientException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
	at com.structurizr.api.WorkspaceApiClient.putWorkspace(WorkspaceApiClient.java:351)
	at com.structurizr.cli.PushCommand.run(PushCommand.java:147)
	at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:83)
	at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:104)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2660)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:741)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2054)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:780)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:5018)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4921)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3868)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3836)
	at com.structurizr.api.ApiResponse.parse(ApiResponse.java:46)
	at com.structurizr.api.WorkspaceApiClient.putWorkspace(WorkspaceApiClient.java:345)
	... 3 more
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1



<img width="253" height="149" alt="Image" src="https://github.com/user-attachments/assets/3b54d03a-ee5b-4ecd-a735-e2f5bcb9d135" />

**Comment by sts-rafalmazgaj** [comment]
@simonbrowndotje do you have any idea where the timeout problem for PUT operations occurs?

**Comment by martinosimard** [comment]
I had a similar issue — maybe not exactly the same, but it looked like it. The problem was caused by a write.lock file that was still open. To resolve it, I had to close the file handle and delete the file from my storage before pushing my workspaces.
